docs/urls.py
from django.urls import path
from . import views

app_name = 'docs'

urlpatterns = [
    path('app_docs/', views.app_docs, name='app_docs'),
    path('user_guide/', views.user_guide, name='user_guide'),
]

sagyodenpyo/urls.py
from django.urls import path
from . import views

app_name = 'sagyodenpyo'

urlpatterns = [
    path('log/', views.log_work, name='log_work'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('loglist/', views.work_logs, name='work_logs'),
    path('list/', views.work_log_list, name='work_log_list'),
    path('edit/<int:pk>/', views.edit_work_log, name='edit_work_log'),
    path('totals/', views.log_totals, name='totals'),
    path('all-logs/', views.all_logs, name='all-logs'),
    path('all_logs_by_date/', views.all_work_logs_by_date, name='all_work_logs_by_date'),  # 新しいURL
    path('export_csv/', views.export_work_logs_csv, name='export_work_logs_csv'),  # CSVダウンロード用URL
    #path('export_pcsv/', views.export_personal_work_logs_csv, name='export_personal_work_logs_csv'), # Export personal logs(to csv)
]

sagyoshiji/urls.py
from django.urls import path
from . import views

app_name = 'sagyoshiji'

urlpatterns = [
    #path('',views.home, name='home'), # root URL  
    path('register/', views.register_work_order, name='register_work_order'),
    path('list/', views.work_order_list, name='work_order_list'),
    path('detail/<int:pk>/', views.work_order_detail, name='work_order_detail'),
    path('delete/<int:pk>/', views.delete_work_order, name='delete_work_order'),
    path('edit/<int:pk>/', views.edit_work_order, name='edit_work_order'),  # 編集用URL
    path('export_csv/', views.export_sagyoshijihyo_csv, name='export_sagyoshijihyo_csv'),  # CSVダウンロード用URL
    path('export_progress_csv/', views.export_workorderprogress_csv, name='export_workorderprogress_csv'),  # CSVダウンロード用URL
    #path('export_pdf/<int:pk>/', views.order_detail_to_pdf, name='export_workorder_pdf' ) # PDF化する
]

ushiku/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sagyodenpyo/', include('sagyodenpyo.urls', namespace='sagyodenpyo')),
    path('sagyoshiji/', include('sagyoshiji.urls'), name='sagyoshiji'),
    path('docs/', include('docs.urls', namespace='docs')),
    path('', include('home.urls', namespace='home')),
    path('login/', auth_views.LoginView.as_view(template_name='home/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),  # 標準の LogoutView を使用
]

sagyodenpyo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class Employee(models.Model):
    employee_number = models.CharField("従業員番号", max_length=10, unique=True)
    name = models.CharField("氏名", max_length=50)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="employee")

    def __str__(self):
        return self.name

class WorkLog(models.Model):
    WORK_CODE_CHOICES = [
        ('001', '001'),
        ('002', '002'),
        ('003', '003'),
        ('004', '004'),
        ('005', '005'),
        ('006', '006'),
        ('007', '007'),
        ('008', '008'),
        ('009', '009'),
        ('010', '010'),
        ('011', '011'),
        ('012', '012'),
        ('013', '013'),
        ('014', '014'),
        ('015', '015'),
        ('016', '016'),
        ('017', '017'),
        ('018', '018'),
        ('019', '019'),
        ('402', '402'),
        ('602', '602'),
        ('701', '701'),
        ('903', '903'),
        ('908', '908'),
        ('909', '909'),
        ('999', '999'),
    ]
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name="work_logs")
    work_number = models.CharField("工番", max_length=4)
    work_trenum = models.CharField("枝番", max_length=3, default="")
    subject = models.CharField("件名", max_length=20)
    work_code = models.CharField("作業コード", max_length=3, choices=WORK_CODE_CHOICES)
    work_hours = models.DecimalField("時間", max_digits=4, decimal_places=0, default="", validators=[MinValueValidator(0), MaxValueValidator(23)])
    work_minute = models.DecimalField("分", max_digits=2, decimal_places=0, default="", validators=[MinValueValidator(0), MaxValueValidator(59)])
    date = models.DateField("作業日", auto_now_add=False)

    def __str__(self):
        return f"{self.employee.name} - {self.work_number} ({self.date})"

sagyodenpyo/forms.py
from django import forms
from .models import WorkLog
from sagyoshiji.models import WorkOrder

class WorkLogForm(forms.ModelForm):
    work_number = forms.ChoiceField(
        choices=[('', '----')] + [(work_number, work_number) for work_number in WorkOrder.objects.filter(work_number__isnull=False).values_list('work_number', flat=True).distinct().order_by('-release_date')],
        label='工番',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    work_trenum = forms.ChoiceField(
        choices=[('', '----')] + [(work_trenum, work_trenum) for work_trenum in WorkOrder.objects.filter(work_trenum__isnull=False, work_number__isnull=False).values_list('work_trenum', flat=True).distinct().order_by('-release_date')],
        label='枝番',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    subject = forms.ChoiceField(
        choices=[('', '----')] + [(subject, subject) for subject in WorkOrder.objects.filter(subject__isnull=False).values_list('subject', flat=True).distinct().order_by('-release_date')],
        label='件名',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    """
    work_number = forms.ModelChoiceField(
        queryset = WorkOrder.objects.filter(work_number__isnull=False).values_list('work_number', flat=True).distinct().order_by('-release_date'),
        empty_label="----",
        label='工番',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    work_trenum = forms.ModelChoiceField(
        queryset=WorkOrder.objects.filter(work_trenum__isnull=False, work_number__isnull=False).values_list('work_trenum', flat=True).distinct().order_by('-release_date'),
        empty_label="----",
        label='枝番',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    subject = forms.ModelChoiceField(
        queryset=WorkOrder.objects.filter(subject__isnull=False).values_list('subject', flat=True).distinct().order_by('-release_date'),
        empty_label="----",
        label='件名',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    
    def __init__(self, *args, **kwargs):
        work_number = kwargs.pop('work_number', None)
        super().__init__(*args, **kwargs)
        if work_number:
            self.fields['work_trenum'].queryset = WorkOrder.objects.filter(
                work_number=work_number,
                work_trenum__isnull = False
            ).distinct().order_by('-release_date')
        else:
            self.fields['work_trenum'].queryset = WorkOrder.objects.none()
    """

    class Meta:
        model = WorkLog
        fields = ['date', 'work_number', 'work_trenum', 'subject', 'work_code', 'work_hours', 'work_minute']
        labels = {
            'date': '作業日',
            'work_number': '工番',
            'work_trenum': '枝番',
            'subject': '件名',
            'work_code': '作業コード',
            'work_hours': '時間',
            'work_minute': '分',
        }
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),  # HTML5の日付入力ウィジェット
            'work_hours': forms.NumberInput(attrs={'min':'0','max':'23'}),
            'work_minute': forms.NumberInput(attrs={'step': '10', 'min':'0', 'max':'50'}),
        }


        

sagyodenpyo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.timezone import now, timedelta
from django.db.models import Sum
from collections import defaultdict
from sagyoshiji.models import WorkOrder
from .models import WorkLog
from .forms import WorkLogForm
import datetime
from django.db.models import Prefetch
from itertools import groupby
from operator import itemgetter


from django.contrib.auth.views import LogoutView
class CustomLogoutView(LogoutView):
    def get(self, request, *args, **kwargs):
        """GET リクエストでもログアウトを許可"""
        return self.post(request, *args, **kwargs)

@login_required
def work_logs(request):
    # 従業員情報の取得
    try:
        employee = request.user.employee
    except employee.DoesNotExist:
        return HttpResponseForbidden("このユーザーには対応する従業員情報がありません。管理者に問い合わせてください。")
        #return render(request, '403.html', {"message":"このユーザーには対応する従業員情報がありません。管理者に問い合わせてください。"})
    
    # 日付範囲の指定
    initial_date = now().date()
    selected_date_str = request.GET.get('selected_date', datetime.datetime.now().strftime('%Y-%m-%d'))
    if selected_date_str:
        try:
            selected_date = datetime.datetime.strptime(selected_date_str, '%Y-%m-%d').date()
        except ValueError:
            selected_date = initial_date

    else:
        selected_date = initial_date


    start_date = selected_date
    end_date = start_date + timedelta(days=7)
        
    # 作業履歴を日付順に取得
    work_logs = WorkLog.objects.filter(employee=employee,date__range=(start_date,end_date)).order_by('date')
    awork_logs = WorkLog.objects.select_related('employee').filter(date__range=(start_date,end_date)).order_by('date', 'employee__name')
    
    # 作業時間の自動計算
    total_hours,remining_minutes = calc_p_wlogs(work_logs)
    # 作業伝票個数表示
    count_logs = work_logs.count()
    # 個人の作業履歴の取得
    an_work_log = WorkLog.objects.filter(employee=employee).order_by('-date') 
    # テンプレートで返す変数群
    context = {
        'work_logs': awork_logs,
        'work_log':an_work_log,
        'total_hours': total_hours,
        'remining_minutes': remining_minutes,
        'cout_logs': count_logs,
        'start_date': start_date,
        'end_date': end_date,
    }

    return render(request, 'sagyodenpyo/view_wlogs.html', context)

# 作業伝票集計
@login_required
def log_totals(request):
    selected_date = request.GET.get('date') or str(datetime.date.today()) 

    try:
        target_date = datetime.date.fromisoformat(selected_date)
    except ValueError:
        target_date = datetime.date.today()

    summary = totaling(target_date)
    context = {
        'selected_date':target_date,
        'count_logss':summary['count_logss'],
        'total_hours': summary['total_hours'],
        'total_minute': summary['total_minute'],
        'order_summary': summary['onum_summary']
    }
    
    return render(request , 'sagyodenpyo/view_totals.html', context)

# 作業伝票登録
@login_required
def log_work(request):
    work_orders = WorkOrder.objects.all().order_by('-release_date')
    if request.method == "POST":
        form = WorkLogForm(request.POST)
        if form.is_valid():
            work_log = form.save(commit=False)
            work_log.employee = request.user.employee  # ログイン中の従業員を紐付け
            work_log.save()
            return redirect('sagyodenpyo:work_logs')
    else:
        form = WorkLogForm()
    return render(request, 'sagyodenpyo/log_work.html', {'form': form, 'work_orders':work_orders})

# 作業伝票修正
@login_required
def edit_work_log(request, pk):
    work_orders = WorkOrder.objects.all().order_by('-release_date')
    work_log = get_object_or_404(WorkLog, pk=pk, employee=request.user.employee)
    if request.method == "POST":
        form = WorkLogForm(request.POST, instance=work_log)
        if form.is_valid():

            form.save()
            return redirect('sagyodenpyo:work_logs')
    else:
        form = WorkLogForm(instance=work_log)
    return render(request, 'sagyodenpyo/edit_work_log.html', {'form': form, 'work_orders':work_orders})

from django.http import HttpResponseForbidden

# 作業履歴一覧(不使用)
@login_required
def work_log_list(request):
    try:
        employee = request.user.employee
    except Employee.DoesNotExist:
        return HttpResponseForbidden("このユーザーには対応する従業員情報がありません。管理者に問い合わせてください。")

    work_logs = WorkLog.objects.filter(employee=employee).order_by('-date')
    return render(request, 'sagyodenpyo/work_log_list.html', {'work_logs': work_logs})

# 全員の作業履歴を取得し、日付ごとにグループ化してテンプレートに渡すビュー(不使用)
@login_required
def all_work_logs_by_date(request):
    # 全ての作業履歴を日付順に取得
    work_logs = WorkLog.objects.select_related('employee').order_by('date', 'employee__name')

    # 日付ごとにグループ化
    grouped_logs = {}
    for date, logs in groupby(work_logs, key=lambda log: log.date):
        grouped_logs[date] = list(logs)

    return render(request, 'sagyodenpyo/all_work_logs_by_date.html', {'grouped_logs': grouped_logs})

#全体の作業履歴のテーブル出力
@login_required
def all_logs(request):
    # 全ての作業履歴を取得
    work_log = WorkLog.objects.all()
    # 存在する日数のカウント
    wl_count = work_log.count()
    return render(request, 'sagyodenpyo/all_wlogs.html', {'work_log':work_log, 'wl_count':wl_count})

#for CSV download
import csv
from django.http import HttpResponse
from .models import WorkLog

@login_required
def export_work_logs_csv(request):
    from urllib.parse import quote
    # CSVレスポンス設定
    filename = f"全体の作業伝票 - {datetime.datetime.now().strftime('%Y%m%d')}.csv"
    encoded_fname = quote(filename)
    response = HttpResponse(content_type='text/csv; charset=shift_jis')
    response['Content-Disposition'] = f"attachment; filename*=UTF-8\'\'{encoded_fname}"

    # Shift-JIS でエンコードされた CSV データを生成
    writer = csv.writer(response, quoting=csv.QUOTE_MINIMAL)

    # ヘッダー行（日本語）
    header = ['従業員名', '工番', '枝番', '件名', '作業コード', '作業時間(時間)', '作業時間(分)', '作業日']
    response.write(",".join(header).encode('shift_jis') + b"\r\n")

    # データ行
    work_logs = WorkLog.objects.select_related('employee').all()
    for log in work_logs:
        row = [
            str(items)

            for items in [
            log.employee.name,
            log.work_number,
            log.work_trenum,
            log.subject,
            log.work_code,
            log.work_hours,
            log.work_minute,
            log.date.strftime("%Y-%m-%d")
            ]
        ]
        response.write(",".join(row).encode('shift_jis') + b"\r\n")

    return response

#個人の作業履歴の出力
"""
@login_required
def export_personal_work_logs_csv(request):
    from urllib.parse import quote
    work_logs = WorkLog.objects.filter(employee=employee).order_by('-date')

    filename = f"{request.user.name}の作業伝票 - {datetime.datetime.now().strftime('%Y%m%d')}.csv"
    encoded_fname = quote(filename)
    response = HttpResponse(content_type='text/csv')
    response['Content-Dispostion'] = f'attachment; filename*=UTF-8\'\'{encoded_fname}'
        # Shift-JIS でエンコードされた CSV データを生成
    writer = csv.writer(response, quoting=csv.QUOTE_MINIMAL)

    # ヘッダー行（日本語）
    header = ['従業員名', '工番', '枝番', '件名', '作業コード', '作業時間(時間)', '作業時間(分)', '作業日']
    response.write(",".join(header).encode('shift_jis') + b"\r\n")

    # データ行
    for log in work_logs:
        row = [
            str(items)

            for items in [
            log.work_number,
            log.work_trenum,
            log.subject,
            log.work_code,
            log.work_hours,
            log.work_minute,
            log.date.strftime("%Y-%m-%d")
            ]
        ]
        response.write(",".join(row).encode('shift_jis') + b"\r\n")

    return response
"""

# other functions

# 個人の作業時間計算周り
def calc_p_wlogs(work_logs):
    # work_hours and work_minutes
    total_work_hours = work_logs.aggregate(total_hours=Sum('work_hours'),total_minute=Sum('work_minute'))

    # calucration of total work hours
    total_hours = total_work_hours['total_hours'] or 0
    total_minute = total_work_hours['total_minute'] or 0
    total_hours += total_minute // 60
    remining_minutes = total_minute % 60

    return total_hours, remining_minutes

# 作業伝票集計・工番とその中に枝番ごとにグループ化
def totaling(target_date):
    logs = WorkLog.objects.filter(date=target_date) #作業履歴を取得
    # 作業伝票個数表示
    count_logss = logs.count()

    totals = logs.aggregate(
        total_hour = Sum('work_hours'),
        total_minute = Sum('work_minute')
    )
    """
    if total_minute >= 60:
        extra_hours = totals.get('total_minute',0) // 60
        totals['total_hour'] = (totals.get('total_hour',0) or 0)+ extra_hours
        totals['total_minute'] = totals.get('total_minute',0) % 60
    """
    total_hours = totals.get('total_hour',0) or 0
    total_minute = totals.get('total_minute',0) or 0
    
    # 工番ごとの集計データを保持する辞書
    onum_summary = defaultdict(lambda: {'total_hours':0, 'total_minute':0, 'trenum_details':[], 'trenum_group':set(), 'subject':set()}) #工番ごとの_合計

    # 工番ごとの集計
    for log in logs:
        onum = log.work_number
        trenum_details = {
            'trenum': log.work_trenum,
            'employee': log.employee,
            'work_code': log.work_code,
            'work_hours': log.work_hours,
            'work_minute': log.work_minute
        }
        onum_summary[onum]['total_hours'] += log.work_hours
        onum_summary[onum]['total_minute'] += log.work_minute

        # 分が60を超えた時の対応
        if onum_summary[onum]['total_minute'] >= 60:
            extra_hours = onum_summary[onum]['total_minute'] // 60
            onum_summary[onum]['total_hours'] += extra_hours
            onum_summary[onum]['total_minute'] = onum_summary[onum]['total_minute'] % 60
            

        onum_summary[onum]['trenum_details'].append(trenum_details)
        onum_summary[onum]['trenum_group'].add(log.work_trenum)
        onum_summary[onum]['subject'].add(log.subject)

    # 必要に応じてセットをリストに変換
    for onum, summary in onum_summary.items():
        summary['trenum_group'] = list(summary['trenum_group'])

sagyodenpyo/templates/sagyodenpyo/all_wlogs.html
{% extends 'base.html' %}

{% block title %}全体の作業伝票一覧 - Ushiku{% endblock %}

{% block content %}
<style>@media screen and (max-width:450px){ table{font-size: small;} }</style>
<div class="subhead">
    <div>
    全体の作業伝票一覧　　
    <a href="{% url 'sagyodenpyo:log_work' %}">新規作成</a>
    <a href="{% url 'sagyodenpyo:work_logs' %}">個人の伝票</a>
    {% if request.user.is_staff %}
    <a href="{% url 'sagyodenpyo:totals' %}">集計</a>
    <a href="{% url 'sagyodenpyo:export_work_logs_csv' %}">全体伝票CSV出力</a>
    {% endif %}
    </div>
    <div>
        伝票件数：<b>{{ wl_count }}件</b>
    </div>
</div>
<div class="subhead_sp">
    <div>
        <div  style="width:600px;">
        全体の作業伝票一覧　　
        <a href="{% url 'sagyodenpyo:log_work' %}">新規作成</a>　
        <a href="{% url 'sagyodenpyo:work_logs' %}">個人の伝票</a>　
        {% if request.user.is_staff %}
        <a href="{% url 'sagyodenpyo:totals' %}">集計</a>　
        <a href="{% url 'sagyodenpyo:export_work_logs_csv' %}">全体伝票CSV出力</a>
        {% endif %}　　

            伝票件数：<b>{{ wl_count }}件</b>
        </div></div>
</div>
<br><br><br>
<div style="width:100%; overflow: auto;">
    <div style="width:700px;">
<table border >
    <thead>
    <tr>
        <th>ID</th>
        <th>日付</th>
        <th>氏名</th>
        <th>工番</th>
        <th>枝番</th>
        <th>件名</th>
        <th>作業コード</th>
        <th>作業時間</th>
    </tr>
    </thead>
    <tbody>
{% for logs in work_log %}
        <tr>
            <td>{{ logs.id }}</td>
            <td>{{ logs.date }}</td>
            <td>{{ logs.employee.name }}</td>
            <td>{{ logs.work_number }}</td>
            <td>{{ logs.work_trenum }}</td>
            <td>{{ logs.subject }}</td>
            <td>{{ logs.get_work_code_display }}</td>
            <td>{{ logs.work_hours }}時間{{ logs.work_minute }}分</td>
        </tr>
{% empty %}
        <tr><td colspan="6">作業伝票はありません。</td></tr>
{% endfor %}
    </tbody><br>
</table></div></div><br><br>
{% endblock %}

sagyodenpyo/templates/sagyodenpyo/view_wlogs.html
{% extends 'base.html' %}

{% block title %}作業履歴 - Ushiku{% endblock %}

{% block content %}
<style>@media screen and (max-width:450px){ h3{font-size: small;} }</style>
<div class="subhead">
    <div>
    作業伝票　　
    <a href="{% url 'sagyodenpyo:log_work' %}">新規作成</a>
    
    {% if request.user.is_staff %}
    <a href="{% url 'sagyodenpyo:all-logs' %}">全体の伝票</a>
    <a href="{% url 'sagyodenpyo:totals' %}">集計</a>
    <!--a href="">個人伝票出力</a-->
    
    
    {% endif %}
    
    </div>
    <div>
        {{ cout_logs }}件見つかりました
    </div>
</div>
<div class="subhead_sp">
    <div><div style="width: 450px;">
    作業伝票　　
    <a href="{% url 'sagyodenpyo:log_work' %}">新規作成</a>　
    
    {% if request.user.is_staff %}
    <a href="{% url 'sagyodenpyo:all-logs' %}">全体の伝票</a>　
    <a href="{% url 'sagyodenpyo:totals' %}">集計</a>　　
    <!--a href="">個人伝票出力</a-->
    {% endif %}
    
        {{ cout_logs }}件見つかりました
    </div></div>
</div>
<br><br><br>

    <div align="center">

        <form method="get" action="{% url 'sagyodenpyo:work_logs' %}">
            <label for="selected_date">開始日を選択</label>
            <input type="date" id="selected_date" name="selected_date" value="{{ start_date|date:'Y-m-d' }}">
            <button type="submit">表示</button>
        </form>

        <div class="alert alert-info mt-3 spmin_h1">
            <strong>{{ start_date|date:"m月 d日" }} から１週間分の作業合計:</strong>
            {{ total_hours }} 時間 {{ remining_minutes }} 分
        </div>
<br>


<br>
    {% if cout_logs > 0 %}
    <div class="wlog_c">
        <h2 style="padding:0; margin:0; ">{{ start_date|date:"m月 d日" }} から１週間分の履歴</h2><br>        
            <table style="margin: 0 auto;"border="1">
                <thead>
                    <tr>
                        <th>作業日</th>
                        <th>工番</th>
                        <th>枝番</th>
                        <th>件名</th>
                        <th>作業コード</th>
                        <th>作業時間</th>
                        <th>分</th>
                        <th>編集</th>
                    </tr>
                </thead>
                <tbody>
                    {% for log in work_logs %}
                    <tr>
                        <td>{{ log.date }}</td>
                        <td>{{ log.work_number }}</td>
                        <td>{{ log.work_trenum }}</td>
                        <td>{{ log.subject }}</td>
                        <td>{{ log.get_work_code_display }}</td>
                        <td>{{ log.work_hours }}</td>
                        <td>{{ log.work_minute }}</td>
                        <td><a href="{% url 'sagyodenpyo:edit_work_log' log.pk %}">&#9998;</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table><br>
            <hr color="skyblue" size="2"width="80%">
            <h2 align="center">” {{ user.first_name }} {{ user.last_name }} ”の作業履歴</h2>
            <p>最新順</p>
            <table style="margin: 0 auto;"border="1">
                <thead>
                    <tr>
                        <!--th>ID</th-->
                        <th>作業日</th>
                        <th>工番</th>
                        <th>枝番</th>
                        <th>件名</th>
                        <th>作業コード</th>
                        <th>作業時間</th>
                        <th>分</th>
                        <th>編集</th>
                    </tr>
                </thead>
                <tbody>
                    {% for logs in work_log %}
                    <tr>
                        <!--td>{{ logs.id }}</td-->
                        <td>{{ logs.date }}</td>
                        <td>{{ logs.work_number }}</td>
                        <td>{{ logs.work_trenum }}</td>
                        <td>{{ logs.subject }}</td>
                        <td>{{ logs.get_work_code_display }}</td>
                        <td>{{ logs.work_hours }}</td>
                        <td>{{ logs.work_minute }}</td>
                        <td><a href="{% url 'sagyodenpyo:edit_work_log' logs.pk %}">&#9998;</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div><br>
        {% else %}
        <div class="wlog_c">
            <h2 style="padding:0; margin:0; ">{{ start_date|date:"m月 d日" }} から１週間分の履歴</h2>
            <h3 align="center">作業履歴はありません。</h3>
            <hr color="skyblue" size="2"width="80%">
            <h2 align="center">” {{ user.first_name }} {{ user.last_name }} ”の作業履歴</h2>
            <p>最新順</p>
            <table style="margin: 0 auto;"border="1">
                <thead>
                    <tr>
                        <!--th>ID</th-->
                        <th>作業日</th>
                        <th>工番</th>
                        <th>枝番</th>
                        <th>件名</th>
                        <th>作業コード</th>
                        <th>作業時間</th>
                        <th>分</th>
                        <th>編集</th>
                    </tr>
                </thead>
                <tbody>
                    {% for logs in work_log %}
                    <tr>
                        <!--td>{{ logs.id }}</td-->
                        <td>{{ logs.date }}</td>
                        <td>{{ logs.work_number }}</td>
                        <td>{{ logs.work_trenum }}</td>
                        <td>{{ logs.subject }}</td>
                        <td>{{ logs.get_work_code_display }}</td>
                        <td>{{ logs.work_hours }}</td>
                        <td>{{ logs.work_minute }}</td>
                        <td><a href="{% url 'sagyodenpyo:edit_work_log' logs.pk %}">&#9998;</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>{% endif %}

    </div><br>
<br>
</div>

{% endblock %}