docs/urls.py
from django.urls import path
from . import views

app_name = 'docs'

urlpatterns = [
    path('app_docs/', views.app_docs, name='app_docs'),
    path('user_guide/', views.user_guide, name='user_guide'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='index'),
    path('user/', views.user_profile, name='user_profile'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
]

sagyoshiji/urls.py
from django.urls import path
from . import views

app_name = 'sagyoshiji'

urlpatterns = [
    #path('',views.home, name='home'), # root URL  
    path('register/', views.register_work_order, name='register_work_order'),
    path('list/', views.work_order_list, name='work_order_list'),
    path('detail/<int:pk>/', views.work_order_detail, name='work_order_detail'),
    path('delete/<int:pk>/', views.delete_work_order, name='delete_work_order'),
    path('edit/<int:pk>/', views.edit_work_order, name='edit_work_order'),  # 編集用URL
    path('export_csv/', views.export_sagyoshijihyo_csv, name='export_sagyoshijihyo_csv'),  # CSVダウンロード用URL
    path('export_progress_csv/', views.export_workorderprogress_csv, name='export_workorderprogress_csv'),  # CSVダウンロード用URL
    #path('export_pdf/<int:pk>/', views.order_detail_to_pdf, name='export_workorder_pdf' ) # PDF化する
]

ushiku/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sagyodenpyo/', include('sagyodenpyo.urls', namespace='sagyodenpyo')),
    path('sagyoshiji/', include('sagyoshiji.urls'), name='sagyoshiji'),
    path('docs/', include('docs.urls', namespace='docs')),
    path('', include('home.urls', namespace='home')),
    path('login/', auth_views.LoginView.as_view(template_name='home/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),  # 標準の LogoutView を使用
]

home/models.py
from django.db import models

sagyoshiji/models.py
from django.db import models

class WorkOrder(models.Model):
    # FB・PL選択
    work_sp_choices = [
        ('FB','FB'),
        ('PL','PL'),
    ]
    # 製作グループ選択
    work_groups = [
        ('牛久工場','牛久工場'),
        ('千葉工場','千葉工場'),
        ('石下工場','石下工場'),
        ('その他','その他'),
    ]
    # 製造工程パターン
    p_pattern = [
        ('No.1','No.1'),
        ('No.2','No.2'),
        ('No.3','No.3'),
        ('No.4','No.4'),
        ('一般工程','一般工程'),
        ('その他','その他'),
    ]


    work_order_number = models.PositiveIntegerField("作業指示票番号", unique=True)  # 7桁の整数
    release_date = models.DateField("発行日", auto_now_add=True)
    work_number = models.CharField("工番", max_length=4)  # 英数字4文字
    work_trenum = models.CharField('枝番', max_length=3, default="") # 英数字３文字
    subject = models.CharField("件名", max_length=20)  # 漢字20文字
    process_pattern = models.CharField("製造工程パタン", max_length=10, choices=p_pattern, default="No.1")  # 英数字10文字
    manager = models.CharField("製造管理担当者", max_length=16)  # 漢字16文字
    work_group = models.CharField('製作グループ', max_length=10, choices=work_groups, default="牛久工場") # 漢字10文字
    work_hours = models.DecimalField("作業工数時間", max_digits=4, decimal_places=1)  # 小数点以下1桁
    next_process = models.CharField("次工程", max_length=20)  # 漢字20文字
    start_date = models.DateField("作業開始日", default="2021/01/01")
    end_date = models.DateField("終了予定日", default="2021/01/10")
    work_type = models.CharField('', max_length=2, choices=work_sp_choices, default="FB")
    work_range = models.CharField('作業範囲', max_length=200, default="P00~00.工00~00")
    planed_value = models.DecimalField('計画数', max_digits=3, decimal_places=0, default="")
    syounin_check = models.CharField('承認', max_length=30, default="", blank=True)
    publish_check = models.CharField('作成', max_length=30, default="", blank=True)
    workset_check = models.CharField('工数設定', max_length=30, default="", blank=True)
    buy_check = models.CharField('購買確認', max_length=30, default="", blank=True)
    recive_check = models.CharField('受け取り確認', max_length=30, default="", blank=True)
    

    def __str__(self):
        return f"{self.work_order_number} - {self.subject}"

    class Meta:
        verbose_name = "作業指示票"
        verbose_name_plural = "作業指示票"

class WorkOrderProgress(models.Model):
    work_order = models.ForeignKey(WorkOrder, on_delete=models.CASCADE, related_name="progresses")
    work_date = models.DateField("作業日", blank=True)
    achievement = models.DecimalField("出来高（％）", max_digits=3, decimal_places=0, default=0, blank=True)
    daily_result = models.DecimalField("当日実績", max_digits=2, decimal_places=0, blank=True)

    def __str__(self):
        return f"{self.work_order} - {self.work_date}"
        

    class Meta:
        verbose_name = "作業進捗"
        verbose_name_plural = "作業進捗"

print(f"startdate >>> {WorkOrder.start_date}")

home/forms.py
from django import forms

sagyoshiji/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import WorkOrder, WorkOrderProgress

class WorkOrderForm(forms.ModelForm):
    class Meta:
        model = WorkOrder
        fields = [
            'work_order_number', 'work_number', 'work_trenum', 'subject', 
            'process_pattern', 'manager', 'work_group', 'work_hours', 
            'next_process', 'start_date', 'end_date', 'work_type', 'work_range', 'planed_value',
            'syounin_check', 'publish_check', 'workset_check', 'buy_check', 'recive_check',
        ]
        labels = {
            'work_order_number': '作業指示票番号(必)',
            'work_number': '工番(必)',
            'work_trenum': '枝番(必)',
            'subject': '件名(必)',
            'process_pattern': '製造工程パタン(必)',
            'manager': '製造管理担当者(必)',
            'work_group': '製作グループ(必)',
            'work_hours': '作業工数時間(必)',
            'next_process': '次工程(必)',
            'start_date': '作業開始日(必)',
            'end_date': '終了予定日(必)',
            'work_range': '作業範囲(必)',
            'planed_value': '計画数(必)',
            'syounin_check': '承認',
            'publish_check': '作成',
            'workset_check': '工数設定',
            'buy_check': '購買確認',
            'recive_check': '受け取り確認',
        }
        widgets = {
            'work_type': forms.RadioSelect(),
            'start_date': forms.TextInput(attrs={'type': 'date'}),
            'end_date': forms.TextInput(attrs={'type': 'date'}),
            'work_range': forms.Textarea(attrs={'resize':'none'}),
            'syounin_check' : forms.TextInput(attrs={'placeholder': '例) 2025/3/10 吉川 将暉'}),
            'publish_check' : forms.TextInput(attrs={'placeholder': '例) 2025/3/11 吉川 将暉'}),
            'workset_check' : forms.TextInput(attrs={'placeholder': '例) 2025/3/12 吉川 将暉'}),
            'buy_check' : forms.TextInput(attrs={'placeholder': '例) 2025/3/13 吉川 将暉'}),
            'recive_check' : forms.TextInput(attrs={'placeholder': '例) 2025/3/14 吉川 将暉'}),
            'work_order_number' : forms.TextInput(attrs={'class': 'sel'}),
            'work_hours' : forms.TextInput(attrs={'class':'sel'}),
        }




# 作業進捗用のフォームßセット
WorkOrderProgressFormSet = inlineformset_factory(
    WorkOrder, WorkOrderProgress,
    fields=('work_date', 'achievement', 'daily_result', ),
    widgets={
        'work_date': forms.TextInput(attrs={'type': 'date','class':'wop_width'}),
    },
    extra=12,  # 12個分のフォームを表示
    max_num=12,
    can_delete=False
)

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from sagyodenpyo.models import WorkLog
from sagyoshiji.models import WorkOrder, WorkOrderProgress
from sagyodenpyo.forms import WorkLogForm
from django.db.models import Sum
from sagyoshiji.views import wprogress_all

import os

from django.contrib.auth.views import LogoutView
class CustomLogoutView(LogoutView):
    def get(self, request, *args, **kwargs):
        """GET リクエストでもログアウトを許可"""
        return self.post(request, *args, **kwargs)

#　ダッシュボードを表示する関数    
@login_required
def home(request):
    try:
        employee = request.user.employee
    except employee.DoesNotExist:
        return HttpResponseForbidden('このユーザーには対応する従業員情報がありません。管理者に問い合わせてください。')
    
    #work_logs = WorkLog.objects.filter(employee=employee).order_by('-date')
    work_orders = WorkOrder.objects.all()

    w_psum = wprogress_all()
    for order in work_orders:
        order.progress_rate = w_psum.get(order.id,0)

    work_order_count = work_orders.count()
    return render(request, 'home/dashboard.html', {'work_orders': work_orders, 'work_order_count':work_order_count,'work_progress': w_psum})

@login_required
def user_profile(request):
    try:
        employee = request.user.employee
    except employee.DoesNotExist:
        return HttpResponseForbidden('このユーザーには対応する従業員情報がありません。管理者に問い合わせてください。')
    wlog = WorkLog.objects.filter(employee=employee).order_by('-date')
    return render(request, 'home/users.html',{'work_log':wlog})

sagyoshiji/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.db import transaction
from collections import defaultdict
import csv
import datetime
from .forms import WorkOrderForm, WorkOrderProgressFormSet
from .models import WorkOrder, WorkOrderProgress
from django.db.models import Sum


# view the 作業指示票一覧
@login_required
def work_order_list(request):
    work_orders = WorkOrder.objects.all().order_by('-release_date')
    w_psum = wprogress_all()
    for order in work_orders:
        order.progress_rate = w_psum.get(order.id,0)

    wo_count = work_orders.count()
    if not work_orders.exists():
        return render(request, 'sagyoshiji/work_order_list.html', {'woerror': '作業指示表のデータが存在しません。登録してください。'})
    return render(request, 'sagyoshiji/work_order_list.html', {'work_orders': work_orders, 'wo_count':wo_count, 'work_progress':w_psum})


# 削除機能のビュー
@login_required
def delete_work_order(request, pk):
    work_order = get_object_or_404(WorkOrder, pk=pk)
    if request.method == "POST":
        work_order.delete()
        return redirect('sagyoshiji:work_order_list')
    return render(request, 'sagyoshiji/delete_work_order.html', {'work_order': work_order})

# view the 作業指示票登録
@login_required
def register_work_order(request):
    if request.method == 'POST':
        form = WorkOrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('sagyoshiji:work_order_list')
    else:
        form = WorkOrderForm()
    return render(request, 'sagyoshiji/register_work_order.html', {'form': form})

# view the 作業指示票修正
@login_required
def edit_work_order(request, pk):
    # 修正する作業指示票を取得
    work_order = get_object_or_404(WorkOrder, pk=pk)
    
    if request.method == 'POST':
        form = WorkOrderForm(request.POST, instance=work_order)
        formset = WorkOrderProgressFormSet(request.POST, instance=work_order)
        if form.is_valid() and formset.is_valid():
            form.save()
            instances = formset.save(commit=False)
            for instance in instances:
                # 必要なフィールドが適切に入力されているか確認
                if instance.daily_result is not None and instance.work_date :
                    print("! check successful")
                    print(f"! instance {instance}")
                    instance.save()
            # 削除が選択されたインスタンスを削除
            for instance in formset.deleted_objects:
                print("! instance was delete")
                instance.delete()
            calc_prate(work_order.id) #作業進捗率を自動で保存
            return redirect('sagyoshiji:work_order_list')
    else:
        form = WorkOrderForm(instance=work_order)
        formset = WorkOrderProgressFormSet(instance=work_order)
    
    return render(request, 'sagyoshiji/edit_work_order.html', {'form': form, 'formset': formset, 'work_order': work_order})

# view the 作業指示票詳細
@login_required
def work_order_detail(request, pk):
    # 指定された作業指示票とその進捗データを取得
    work_order = get_object_or_404(WorkOrder, pk=pk)
    work_orders= WorkOrderProgress.objects.filter(work_order=work_order)  # 関連する進捗データを取得
    w_psum = wprogress_all()
    
    work_order.progress_rate = w_psum.get(work_order.id,0)#各作業指示における進捗率合計

    return render(request, 'sagyoshiji/work_order_detail.html', {
        'work_order': work_order,
        'work_orders': work_orders,
        'work_progress': w_psum,
    })

#CSV and PDF download support

@login_required
def export_sagyoshijihyo_csv(request):
    from urllib.parse import quote
    # CSVレスポンス設定
    filename = f"作業指示票 - {datetime.datetime.now().strftime('%Y%m%d')}.csv"
    encoded_fname = quote(filename) # URL encode
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f"attachment; filename*=UTF-8\'\'{encoded_fname}"

    # Shift-JIS エンコーディング
    response.write(u'\ufeff'.encode('utf-8-sig'))  # BOM追加（Excel対応）
    writer = csv.writer(response)
    # ヘッダー行
    writer.writerow([
        '作業指示票番号', '工番', '件名', '製造工程パタン', '製造管理担当者',
        '作業工数時間', '次工程', '作業開始日', '終了予定日'
    ])

    # 作業指示票データを取得してCSVに書き込む
    sagyoshijihyo_list = WorkOrder.objects.all()
    for shiji in sagyoshijihyo_list:
        writer.writerow([
            shiji.id,
            shiji.work_number,
            shiji.subject,
            shiji.process_pattern,
            shiji.manager,
            shiji.work_hours,
            shiji.next_process,
            shiji.start_date,
            shiji.end_date,
        ])

    return response


@login_required
def export_workorderprogress_csv(request):
    from urllib.parse import quote
    # CSVレスポンス設定
    filename = f"全体の作業進捗 - {datetime.datetime.now().strftime('%Y%m%d')}.csv"
    encoded_fname = quote(filename)
    response = HttpResponse(content_type='text/csv; charset=shift_jis')
    response['Content-Disposition'] = f"attachment; filename*=UTF-8\'\'{encoded_fname}"

    writer = csv.writer(response, quoting=csv.QUOTE_MINIMAL)

    # ヘッダー行
    writer.writerow([
        '進捗ID', '作業指示票番号', '作業日', '出来高（％）', '当日実績'
    ])

    # データ行
    progress_list = WorkOrderProgress.objects.select_related('work_order').all()
    for progress in progress_list:
        writer.writerow([
            progress.id,
            progress.work_order.work_order_number if progress.work_order else 'なし',
            progress.work_date.strftime('%Y-%m-%d'),
            progress.achievement,
            progress.daily_result,
        ])

    return response

# 作業進捗率の計算
def calc_prate(work_order_id):
    progress_data = WorkOrderProgress.objects.filter(work_order_id=work_order_id)
    with transaction.atomic():
        for progress in progress_data:
            # 作業指示票の計画値を取得
            work_order = progress.work_order
            if work_order:
                planed_value = work_order.planed_value
                # 作業進捗率を計算
                if planed_value > 0:
                    progress_rate = (progress.daily_result / planed_value) * 100
                    rounded_rate = round(progress_rate, 2)
                    if progress.achievement != rounded_rate:
                        progress.achievement = rounded_rate
                        progress.save()
                else:
                    if progress.achievement != 0:
                        # 計画値が0の場合、進捗率を0にリセット
                        progress.achievement = 0
                        progress.save()

# 作業進捗の合計の計算
def wprogress_all():
    # get all progress data
    progress_totals = defaultdict(float)
    progress_all = WorkOrderProgress.objects.values('work_order_id').annotate(total_pall=Sum('achievement'))
    
    
    for progress in progress_all:
        worder_id = progress['work_order_id']
        total_pall = float(progress['total_pall'] or 0)
        progress_totals[worder_id] += round(total_pall, 2)
    
    return dict(progress_totals)

sagyoshiji/templates/sagyoshiji/delete_work_order.html
{% extends 'base.html' %}

{% block title %}作業指示票削除 - Ushiku{% endblock %}

{% block content %}
<div class="subhead"><div>作業指示票削除　　</div></div>
<div class="subhead_sp"><div>作業指示票削除　　</div></div>
<br><br>
    <p>以下の作業指示票を削除してもよろしいですか？</p>

    <h3><u>作業指示表番号：{{ work_order.work_order_number }}</u></h3>
    <h2><u>工番：{{ work_order.work_number }}</u></h2>
    <h2><u>枝番：{{ work_order.work_trenum }}</u></h2>
    <h1><u>件名：{{ work_order.subject }}</u></h1>

    <form method="post">
        {% csrf_token %}
        <br><br>
        <style>@media screen and (max-width:450px){.f_el{position: fixed; bottom:5%;}}</style>
        <div class="f_el"><div align="right">
            <a href="#" onclick="history.back();" >キャンセル</a>　
            <button type="submit" class="sub_bt" style="padding:10px 20px;">削除する</button>
        </div></div>
    </form><br>
{% endblock %}

sagyoshiji/templates/sagyoshiji/edit_work_order.html
{% extends 'base.html' %}

{% block title %}作業指示票修正 - Ushiku{% endblock %}

{% block content %}
<div class="subhead">
    <div>
    作業指示票修正　　No.{{ work_order.work_order_number }}
    <label class="ank" id="progress">作業進捗登録</label>
    </div>
</div>
<div class="subhead_sp">
    <div>
    作業指示票修正　　No.{{ work_order.work_order_number }}
    </div>
</div>
<br><br>
<style>@media screen and (max-width:450px){label{font-size: small;}}</style>
<div class="form_formera">
    <form method="post" >
        {% if request.user.is_superuser or request.user.is_staff %}
        <div align="center"><h2 class="titles">作業指示票情報</h2></div>  
        {% csrf_token %}      
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <!-- form.as_p -->
        <div  class="form_former">
            <div style="padding:10px; text-align: right;" >
                {{ form.work_order_number.label_tag }}
                {{ form.work_order_number }}<br>
    
                {{ form.work_number.label_tag }}
                {{ form.work_number }}<br>
    
                {{ form.work_trenum.label_tag }}
                {{ form.work_trenum }}<br>
    
                {{ form.subject.label_tag }}
                {{ form.subject }}<br>
    
                {{ form.process_pattern.label_tag }}
                {{ form.process_pattern }}<br>
    
                {{ form.manager.label_tag }}
                {{ form.manager }}<br>
    
                {{ form.work_group.label_tag }}
                {{ form.work_group }}<br>
    
                {{ form.work_hours.label_tag }}
                {{ form.work_hours }}
            </div>
            <div style="padding:10px; text-align: right;" >
                {{ form.next_process.label_tag }}
                {{ form.next_process }}<br>
                
                {{ form.start_date.label_tag }}
                {{ form.start_date }}<br>
                
                {{ form.end_date.label_tag }}
                {{ form.end_date }}<br>
                
                {{ form.planed_value.label_tag }}
                {{ form.planed_value }}<br><br>
                
                {{ form.syounin_check.label_tag }}
                {{ form.syounin_check }}<br>
                
                {{ form.publish_check.label_tag }}
                {{ form.publish_check }}<br>
                
                {{ form.workset_check.label_tag }}
                {{ form.workset_check }}<br>
                
                {{ form.buy_check.label_tag }}
                {{ form.buy_check }}<br>
                
                {{ form.recive_check.label_tag }}
                {{ form.recive_check }}
            </div>
            <div style="padding:10px; text-align: left;">
                <div class="work_rangesf">
                <b>作業範囲</b><br>
                    {{ form.work_range }}
                    
                    {% for radio in form.work_type %}
                    <label >
                    {{ radio.tag }} {{ radio.choice_label }}
                    </label>
                    {% endfor %}
                </div>
            </div>
    
    </div>
    {% endif %}
        <div align="center"><h2 class="titles">作業進捗データ</h2></div>
        <div style="width:100%; overflow: auto;">
            <div align="center">
        {{ formset.management_form }}
        <table>
            <thead>
                <tr>
                    <th>作業日</th>
                    <th>当日実績</th>
                </tr>
            </thead>
            <tbody>
                {% for form in formset %}
                <tr>
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                    <td>{{ form.work_date }}</td>
                    <td>{{ form.daily_result }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div></div><br><br>
        <div class="f_el"><div align="right">
            <!--a href="{% url 'sagyoshiji:work_order_list' %}" >一覧に戻る</a-->　
            <button class="sub_bt" onclick="history.back(); return false;">戻る</button>　
            <button type="submit" class="sub_bt" style="padding:10px 20px;">登録</button>
        </div></div>    </form></div><br>

        <script>
            //ボタンを押したら指定箇所にスクロール
            //const collectorder = document.querySelector('#shiji');
            const collectprogress = document.querySelector('#progress');
/*
            collectorder.addEventListener('click' , function(){
                window.scrollBy({
                    top:100,
                    behavior:'smooth'
                })
                console.log('! collect order');
            });
*/
            collectprogress.addEventListener('click', function(){
                window.scrollBy({
                    top:600,
                    behavior:'smooth'
                })
                console.log('! collect prosess');
            });
        </script><style>main{width:100%;}</style>
        <script>
            // フォーム内でEnterキーを押したときのデフォルト動作を無効化
            document.querySelectorAll('form').forEach(form => {
                form.addEventListener('keypress', function(event) {
                    if (event.key === 'Enter') {
                        // Enterキーが押された場合、デフォルトの送信動作を防ぐ
                        event.preventDefault();
                    }
                });
            });
        </script>
{% endblock %}

sagyoshiji/templates/sagyoshiji/home.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>牛久工場工程管理システム</title>
</head>
<body>
    <h1>牛久工場工程管理システム</h1>
    <ul>
        <li><a href="/list/">作業指示一覧</a></li>
        <li><a href="/login/">作業伝票ログイン</a></li>
    </ul>
</body>
</html>

sagyoshiji/templates/sagyoshiji/work_order_list.html
{% extends 'base.html' %}

{% block title %}作業指示票 - Ushiku{% endblock %}

{% block content %}

<div class="subhead">
    <div>
    作業指示票一覧　　
    {% if request.user.is_superuser %}
    <a href="{% url 'sagyoshiji:register_work_order' %}">新規作成</a>
    {% if work_orders %}
    <a href="{% url 'sagyoshiji:export_sagyoshijihyo_csv' %}" >作業指示票CSV出力</a>
    <a href="{% url 'sagyoshiji:export_workorderprogress_csv' %}" >作業進捗CSV出力</a>
    {% endif %}{% endif %}
    </div>
    <div>
        作業指示票件数：{{ wo_count }}件
    </div>
</div>
<div class="subhead_sp">
    <div>
        <div style="width:610px;">
    作業指示票一覧　　
    {% if request.user.is_staff %}
    <a href="{% url 'sagyoshiji:register_work_order' %}">新規作成</a>　
    {% if work_orders %}
    <a href="{% url 'sagyoshiji:export_sagyoshijihyo_csv' %}" >作業指示票CSV出力</a>　
    <a href="{% url 'sagyoshiji:export_workorderprogress_csv' %}" >作業進捗CSV出力</a>　
    {% endif %}{% endif %}
    　<b>作業指示票件数：{{ wo_count }}件</b>
    </div></div>
</div>
<br><br><br>

    
    {% if not work_orders %}
        <h1>データがありません</h1>
        <p>「新規作成」から作成</p>
    {% else %}
    {% for order in work_orders %}
    <a href="{% url 'sagyoshiji:work_order_detail' order.pk %}" style="text-decoration: none; color:black;" title="作業指示の詳細を確認する">
    <div class="wo_list">
        
            <p align="left">作業指示番号：{{ order.work_order_number }}　/　発行日：{{ order.release_date }}</p>
            <h2><u>工番-枝番：{{ order.work_number }}ー{{ order.work_trenum }} / 件名：{{ order.subject }}</u></h2>
            <p>計画数：{{ order.planed_value }}、作業開始日：{{ order.start_date }}、作業終了日{{ order.end_date }}</p>
            <p>作業範囲：{{ order.work_range }} ｜ {{ order.work_type }}</p>
            <p>作業進捗率：{{ order.progress_rate }}%</p>
            <hr color="gray" size="1" width="50%">
            <a href="{% url 'sagyoshiji:edit_work_order' order.pk %}" class="up_del">修正・作業進捗登録</a>　
            {% if request.user.is_superuser %}
            <a href="{% url 'sagyoshiji:delete_work_order' order.pk %}" class="up_del">削除</a>
            {% endif %}
            <br>
    </div></a>
    <a href="{% url 'sagyoshiji:work_order_detail' order.pk %}" style="text-decoration: none; color:black;" title="作業指示の詳細を確認する">
    <div class="wo_list_sp">
        <p align="left" style="font-size: small; padding:1px;">作業指示番号：{{ order.work_order_number }} / 発行日：{{ order.release_date }}</p>
        <h3><u>工番-枝番：{{ order.work_number }}ー{{ order.work_trenum }} </h3><h1> 件名：{{ order.subject }}</u></h1>
        <h3>計画数：{{ order.planed_value }}</h3>
        <p style="font-size: large;">作業期間：{{ order.start_date }} ~ {{ order.end_date }}</p>
        <p>作業範囲：{{ order.work_range }} <br> {{ order.work_type }}</p>
        <h4>作業進捗率：{{ order.progress_rate }}%</h4>
        <hr color="gray" size="1" width="50%"><br>
        <a href="{% url 'sagyoshiji:edit_work_order' order.pk %}" class="up_del">修正・作業進捗登録</a>　
        {% if request.user.is_superuser %}
        <a href="{% url 'sagyoshiji:delete_work_order' order.pk %}" class="up_del">削除</a>
        {% endif %}
        <br>
    </div></a><br><br>
        {% endfor %}
    {% endif %}

{% endblock %}