docs/urls.py
from django.urls import path
from . import views

app_name = 'docs'

urlpatterns = [
    path('app_docs/', views.app_docs, name='app_docs'),
    path('user_guide/', views.user_guide, name='user_guide'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='index'),
    path('user/', views.user_profile, name='user_profile'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
]

sagyodenpyo/urls.py
from django.urls import path
from . import views

app_name = 'sagyodenpyo'

urlpatterns = [
    path('log/', views.log_work, name='log_work'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('loglist/', views.work_logs, name='work_logs'),
    path('list/', views.work_log_list, name='work_log_list'),
    path('edit/<int:pk>/', views.edit_work_log, name='edit_work_log'),
    path('totals/', views.log_totals, name='totals'),
    path('all-logs/', views.all_logs, name='all-logs'),
    path('all_logs_by_date/', views.all_work_logs_by_date, name='all_work_logs_by_date'),  # 新しいURL
    path('export_csv/', views.export_work_logs_csv, name='export_work_logs_csv'),  # CSVダウンロード用URL
    #path('export_pcsv/', views.export_personal_work_logs_csv, name='export_personal_work_logs_csv'), # Export personal logs(to csv)
]

sagyoshiji/urls.py
from django.urls import path
from . import views

app_name = 'sagyoshiji'

urlpatterns = [
    #path('',views.home, name='home'), # root URL  
    path('register/', views.register_work_order, name='register_work_order'),
    path('list/', views.work_order_list, name='work_order_list'),
    path('detail/<int:pk>/', views.work_order_detail, name='work_order_detail'),
    path('delete/<int:pk>/', views.delete_work_order, name='delete_work_order'),
    path('edit/<int:pk>/', views.edit_work_order, name='edit_work_order'),  # 編集用URL
    path('export_csv/', views.export_sagyoshijihyo_csv, name='export_sagyoshijihyo_csv'),  # CSVダウンロード用URL
    path('export_progress_csv/', views.export_workorderprogress_csv, name='export_workorderprogress_csv'),  # CSVダウンロード用URL
    #path('export_pdf/<int:pk>/', views.order_detail_to_pdf, name='export_workorder_pdf' ) # PDF化する
]

ushiku/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sagyodenpyo/', include('sagyodenpyo.urls', namespace='sagyodenpyo')),
    path('sagyoshiji/', include('sagyoshiji.urls'), name='sagyoshiji'),
    path('docs/', include('docs.urls', namespace='docs')),
    path('', include('home.urls', namespace='home')),
    path('login/', auth_views.LoginView.as_view(template_name='home/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),  # 標準の LogoutView を使用
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#ffffff">
    <title>{% block title %}Ushiku{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'ico/shirayama_app_mm.png' %}" >
    <link rel="manifest" href="{% static 'pwa/manifest.json' %}">
    <script>
        if('serviceWorker' in navigator){
            navigator.serviceWorker.register("{% static 'pwa/service-worker.js' %}");
            /*.then(function(registration){
                console.log('Service Worker registered with scope:', registration.scope);
            }).catch(function(err){
                console.log('Service Worker registration failed:', err);
            });*/
        }
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function(){
            let color = '#5dccfa';
            document.querySelector('meta[name="theme-color"]').setAttribute('content', color);
        });
    </script>
    <script>
        //スマホ版戻るボタンの表示制御
        const back_button = document.getElementById('spbb');
        if(window.history.length > 1){
            back_button.style.display = 'block';
        }else{
            back_button.style.display = 'none';
        }
    </script>
</head>
<body>
    <header class="printnot">
        <div class="hsu printnot hsel">

        <a href="/" class="hm"><img src="{% static 'ico/shirayama_app_mm.png' %}" class="h_icon" alt="HOME"><b style="font-size: large;">Ushiku</b></a>
        <a href="{% url 'sagyoshiji:work_order_list' %}"class="hm">作業指示票</a>
        <a href="{% url 'sagyodenpyo:work_logs' %}" class="hm">作業伝票</a>     
        </div>
        
        <div class="hsu printnot hsel">

            <!--a href="tel:0298698330" class="hm"><img src="{% static 'svgs/call.svg' %}" class="h_icon" alt="電話"></a-->
            <a href="{% url 'docs:app_docs' %}" class="hm"><img src="{% static 'svgs/question.svg' %}" class="h_icon" alt="ヘルプ"></a>

        {% if user.is_authenticated %}
        <a href="{% url 'home:user_profile' %}" style="text-decoration: none;"><span class="userbox"><img src="{% static 'svgs/user.svg' %}" class="h_icon"> {{ user.id|stringformat:"03d" }} : {{ user.first_name }} {{ user.last_name }} </span></a>　
        <form action="{% url 'logout' %}" method="post" style="display:inline;">
            {% csrf_token %}
            <button type="submit" onclick="return confirm('ログアウトしてもよろしいですか？');">ログアウト</button>
        </form>
    {% else %}
        <a href="{% url 'login' %}" class="hm">ログイン</a>
        <script>
            location.href = "{% url 'login' %}";
        </script>
    {% endif %}
    {% if request.user.is_superuser %}
    <a href="{% url 'admin:index' %}" class="hm" onclick="return alert('管理画面に移動します。');">アカウント管理</a>　
    {% endif %}
    </div>
    <div class="hsu printnot hsonl">
        <a href="#" class="hm" onclick="history.back(); return false;" id="spbb">＜</a> 
        <img src="{% static 'ico/shirayama_app_mm.png' %}" class="h_icon" alt="HOME"><b style="font-size: large;">Ushiku</b>
    </div>
    <div class="hsu printnot hsonl">
        {% if request.user.is_superuser %}
        <a href="{% url 'admin:index' %}" class="hm" onclick="return alert('管理画面に移動します。');">アカウント管理</a>　
        {% endif %}
        <a href="{% url 'docs:app_docs' %}" class="hm"><img src="{% static 'svgs/question.svg' %}" class="h_icon" alt="ヘルプ"></a>
    </div>
    </header>
    <br><br><br>
    <main>
        <div align="center">
        
        {% block content %}
        {% endblock %}

        </div>
    </main><br>
    <div class="menus"><div align="center">
        <a href="/" class="hm"><img src="{% static 'svgs/home.svg' %}" class="h_icon" alt="HOME"></a>
        <a href="{% url 'sagyoshiji:work_order_list' %}"class="hm">作業指示票</a>
        <a href="{% url 'sagyodenpyo:work_logs' %}" class="hm">作業伝票</a>  
        <a href="{% url 'home:user_profile' %}" style="text-decoration: none;"><span class="userbox"><img src="{% static 'svgs/user.svg' %}" class="h_icon" style="border: 1px solid dimgray; border-radius: 5px; padding:3px 5px;"></span></a>　

    </div></div>
    <script src="{% static 'scripts/focus.js' %}"></script>
    <noscript>
        <h1 align="center">Javascriptの設定を確認してください。</h1>
        <p>JavaScriptが無効なため本サイトにアクセスできません。</p>
        <p>JavaScriptを有効にしてページを更新してください。</p>
    </noscript>
</body>
</html>

templates/docs_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#ffffff">
    <title>{% block title %}Ushiku Docs{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'ico/shirayama_app_mm.png' %}" >
    <link rel="manifest" href="{% static 'pwa/manifest.json' %}">
    <script>
        if('serviceWorker' in navigator){
            navigator.serviceWorker.register("{% static 'pwa/service-worker.js' %}");
            /*.then(function(registration){
                console.log('Service Worker registered with scope:', registration.scope);
            }).catch(function(err){
                console.log('Service Worker registration failed:', err);
            });*/
        }
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function(){
            let color = '#5dccfa';
            document.querySelector('meta[name="theme-color"]').setAttribute('content', color);
        });
    </script>
    <script>
        //スマホ版戻るボタンの表示制御
        const back_button = document.getElementById('spbb');
        if(window.history.length > 1){
            back_button.style.display = 'block';
        }else{
            back_button.style.display = 'none';
        }
    </script>
</head>
<body>
    <header class="printnot">
        <div class="hsu printnot hsel">

        <a href="/" class="hm"><img src="{% static 'ico/shirayama_app_mm.png' %}" class="h_icon" alt="HOME"><b style="font-size: large;">Ushiku</b></a>
        <a href="{% url 'sagyoshiji:work_order_list' %}"class="hm">作業指示票</a>
        <a href="{% url 'sagyodenpyo:work_logs' %}" class="hm">作業伝票</a>     
        </div>
        
        <div class="hsu printnot hsel">

            <a href="tel:0298698330" class="hm" title="牛久工場へ電話をかける"><img src="{% static 'svgs/call.svg' %}" class="h_icon" alt="電話"></a>
            <a href="{% url 'docs:app_docs' %}" class="hm"><img src="{% static 'svgs/question.svg' %}" class="h_icon" alt="ヘルプ"></a>

        {% if user.is_authenticated %}
        <a href="{% url 'home:user_profile' %}" style="text-decoration: none;"><span class="userbox"><img src="{% static 'svgs/user.svg' %}" class="h_icon"> {{ user.id|stringformat:"03d" }} : {{ user.first_name }} {{ user.last_name }} </span></a>　
        <form action="{% url 'logout' %}" method="post" style="display:inline;">
            {% csrf_token %}
            <button type="submit" onclick="return confirm('ログアウトしてもよろしいですか？');">ログアウト</button>
        </form>
    {% else %}
        <a href="{% url 'login' %}" class="hm">ログイン</a>
        <script>
            location.href = "{% url 'login' %}";
        </script>
    {% endif %}
    {% if request.user.is_superuser %}
    <a href="{% url 'admin:index' %}" class="hm" onclick="return alert('管理画面に移動します。');">アカウント管理</a>　
    {% endif %}
    </div>
    <div class="hsu printnot hsonl">
        <a href="#" class="hm" onclick="history.back(); return false;" id="spbb">＜</a> 
        <img src="{% static 'ico/shirayama_app_mm.png' %}" class="h_icon" alt="HOME"><b style="font-size: large;">Ushiku</b>
    </div>
    <div class="hsu printnot hsonl">
        {% if request.user.is_superuser %}
        <a href="{% url 'admin:index' %}" class="hm" onclick="return alert('管理画面に移動します。');">アカウント管理</a>　
        {% endif %}         
        
        <a href="tel:0298698330" class="hm" title="牛久工場へ電話をかける"><img src="{% static 'svgs/call.svg' %}" class="h_icon" alt="電話"></a>
        <a href="{% url 'docs:app_docs' %}" class="hm"><img src="{% static 'svgs/question.svg' %}" class="h_icon" alt="ヘルプ"></a>
    </div>
    </header>
    <br><br><br>
    <main>
        <div align="center">
        <!--div class="mokuji">
            <h3>目次</h3>
            <ol align="left">
                <li><a href="{% url 'docs:app_docs' %}">ホーム</a></li>
                <ol>
                    <li><a href="/docs/app_docs/#about">本アプリについて</a></li>
                </ol>
                <li><a href="{% url 'docs:user_guide' %}">ユーザーガイド</a></li>
                <ol>
                    <li><a href="/docs/user_guide/#1">aaa</a></li>
                </ol>
            </ol>
        </div-->

        <h1 id="-" align="center">Ushiku</h1>
        <h3 id="-">ドキュメントページ</h3>
        <div align="center" class="content">
        {% block content %}
        {% endblock %}
        </div>
        </div>
    </main>
    <div class="menus"><div align="center">
        <a href="/" class="hm"><img src="{% static 'svgs/home.svg' %}" class="h_icon" alt="HOME"></a>
        <a href="{% url 'sagyoshiji:work_order_list' %}"class="hm">作業指示票</a>
        <a href="{% url 'sagyodenpyo:work_logs' %}" class="hm">作業伝票</a>  
        <a href="{% url 'home:user_profile' %}" style="text-decoration: none;"><span class="userbox"><img src="{% static 'svgs/user.svg' %}" class="h_icon" style="border: 1px solid dimgray; border-radius: 5px; padding:3px 5px;"></span></a>　

    </div></div>
    <noscript>
        <h1 align="center">Javascriptの設定を確認してください。</h1>
        <p>JavaScriptが無効なため本サイトにアクセスできません。</p>
        <p>JavaScriptを有効にしてページを更新してください。</p>
    </noscript>
</body>
</html>